{ pkgs, ...}:
{
    environment.systemPackages = with pkgs; [
        adwsteamgtk
        anki
        bartib
        bat
        bottles
        brave
        btop
        dconf2nix
        deluge
        fastfetch
        fd
        ferdium
        file
        gcc
        gdu
        ghostty
        git
        gnome-podcasts
        gnome-tweaks
        gnome-user-share
        gnome-weather
        gnomeExtensions.appindicator
        gnomeExtensions.auto-accent-colour
        gnomeExtensions.dash-to-dock
        gnomeExtensions.forge
        gnomeExtensions.night-theme-switcher
        gnomeExtensions.rounded-window-corners-reborn
        gnumake
        gnupg
        heroic
        hledger
        hledger-iadd
        imagemagick # auto-accent requires it
        inkscape
        kitty
        libnotify
        libreoffice
        lutris
        micro
        mousam # weather
        mpv
        newsflash
        nodejs-slim
        obsidian
        p7zip
        pass
        pinentry-gnome3
        prismlauncher
        puffin
        python3
        renameutils
        ripgrep
        ripgrep-all
        stow
        stretchly # no breaktimer on nix
        swaynotificationcenter
        texliveFull
        thunderbird
        tokei
        tree-sitter
        unrar-free
        unzip
        varia
        vesktop
        wl-clipboard
        wofi
        yazi
        zathura
        zotero
        zsh-powerlevel10k
    ];
}
