{ pkgs, ...}:
{
    environment.systemPackages = with pkgs; [
        adwsteamgtk
        anki
        bartib
        bat
        bottles
        brave
        btop
        deluge
        fastfetch
        fd
        ferdium
        file
        fzf
        gcc
        gdu
        git
        gnome-podcasts
        gnome-tweaks
        gnome-user-share
        gnomeExtensions.appindicator
        gnomeExtensions.dash-to-dock
        gnomeExtensions.forge
        gnomeExtensions.night-theme-switcher
        gnomeExtensions.rounded-window-corners-reborn
        gnumake
        gnupg
        heroic
        hledger
        hledger-iadd
        inkscape
        kitty
        libnotify
        libreoffice
        lsd
        lutris
        micro
        mousam
        mpv
        nodejs-slim
        obsidian
        p7zip
        pass
        pinentry-gnome3
        plex-desktop
        plex-media-player
        prismlauncher
        puffin
        python3
        renameutils
        ripgrep
        ripgrep-all
        stow
        stretchly # no breaktimer on nix
        swaynotificationcenter
        texliveFull
        thunderbird
        tmux
        tree-sitter
        unrar-free
        unzip
        varia
        vesktop
        wl-clipboard
        wofi
        yazi
        zathura
        zotero
        zoxide
        zsh-powerlevel10k
    ];
}
