# Run zathura as the pdf viewer, cant remember what the arguments are for
$pdf_previewer = 'zathura %O %S';

# Tell it to make a pdf directly using pdflatex
# $pdf_mode = 1;

# Might need to pass extra flags to pdflatex e.g:
# $pdflatex = 'pdflatex -shell-escape';

# Run bibtex or biber whenever it appears necessary to update the bbl files
# without checking for the existence of the bib files
# i.e. presume whatever it's compiling has access to the bib file.
# This means they will get deleted in a cleanup.
# $bibtex_use = 2;

# Clean up some extra bits from slides
# $clean_full_ext = 'bbl-SAVE-ERROR nav run.xml snm tex.bbl tex.blg vrb';

# Tell it what the main file is if there are multiple
# @default_files = ('file.tex');
