# keyboard
xkb_rules_layout=gb
numlockon=1
xkb_rules_options=caps:escape

# mouse
# need relogin to make it apply
mouse_natural_scrolling=1

# monitors
# desktop wide montor
monitorrule=serial:UMW090HA,x:0,y:0

# Iiyama desktop vertical monitor
monitorrule=serial:1154115101184,rr:1,x:2560,y:-525

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+Shift,r,reload_config

# menu and terminal
# bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,space,spawn,rofi -show combi -combi-modes window,drun -modes combi,emoji:rofimoji,calc -show-icons
# -calc-command "echo -n '{result}' | wl-copy"; 
bind=SUPER,Return,spawn,ghostty
bind=Super,b,spawn,firefox

# exit
bind=Super+Shift,e,quit
bind=SUPER+SHIFT,q,killclient,

# switch window focus
# tabbing
bind=Super,Tab,focusstack,next

# arrows
bind=Super,Left,focusdir,left
bind=Super,Right,focusdir,right
bind=Super,Up,focusdir,up
bind=Super,Down,focusdir,down

# vim hjkl
bind=Super,h,focusdir,left
bind=Super,l,focusdir,right
bind=Super,k,focusdir,up
bind=Super,j,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

bind=Super,f,togglefullscreen,
bind=Super+Shift,f,togglefakefullscreen,
bind=Super+Ctrl,f,togglemaximizescreen,

# switch layout
bind=SUPER,n,switch_layout

# view tags
bind=Super,1,view,1,0
bind=Super,2,view,2,0
bind=Super,3,view,3,0
bind=Super,4,view,4,0
bind=Super,5,view,5,0
bind=Super,6,view,6,0
bind=Super,7,view,7,0
bind=Super,8,view,8,0
bind=Super,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=Super+Shift,1,tag,1,0
bind=Super+Shift,2,tag,2,0
bind=Super+Shift,3,tag,3,0
bind=Super+Shift,4,tag,4,0
bind=Super+Shift,5,tag,5,0
bind=Super+Shift,6,tag,6,0
bind=Super+Shift,7,tag,7,0
bind=Super+Shift,8,tag,8,0
bind=Super+Shift,9,tag,9,0
